### ISSUE TITLE
Another Null Pointer Exception on Runnable

### ISSUE THREAD

**Issue by WaiLynnZaw** [darsh2/MultipleImageSelect#16]
I am not sure if it is related with issue #14  and I got this error. (My android version is - 6.0.1 and I am using v.0.0.4 of multiple image select library)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                                 at java.io.File.fixSlashes(File.java:183)
                                                                                 at java.io.File.<init>(File.java:130)
                                                                                 at com.darsh.multipleimageselect.activities.AlbumSelectActivity$AlbumLoaderRunnable.run(AlbumSelectActivity.java:353)
                                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by darsh2** [comment]
As far as I know, it is not related with issue #14 . I could recreate this error by doing image = null. Problem is in line 353 in AlbumSelectActivity (v0.0.4), String image is null. Does this always occur or is it only in specific use cases?

**Comment by WaiLynnZaw** [comment]
What do you mean "image = null". It is only occur in one device when i test with about 3 devices. Thanks

**Comment by darsh2** [comment]
In the following snippet:

```java
String album = cursor.getString(cursor.getColumnIndex(projection[0]));
String image = cursor.getString(cursor.getColumnIndex(projection[1]));

/*
It may happen that some image file paths are still present in cache,
though image file does not exist. These last as long as media
scanner is not run again. To avoid get such image file paths, check
if image file exists.
 */
file = new File(image);
```

by adding
```java
image = null;
```
just before the statement
```java
file = new File(image);
```
I could recreate the error in the device I tested on. This occurs probably because
```java
String image = cursor.getString(cursor.getColumnIndex(projection[1])); 
```
cursor.getString returns null. Quoting from the [documentation](http://developer.android.com/reference/android/database/Cursor.html#getString(int)):

"The result and whether this method throws an exception when the column value is null or the column type is not a string type is implementation-defined."

Will look into this. Quick fix solution would be:
```java
if (image == null) {
    return;
}
file = new File(image);
```

I'd appreciate any pull requests to fix this.
