### ISSUE TITLE
Bunch of Null Pointer Exceptions 

### ISSUE THREAD

**Issue by BassDay** [darsh2/MultipleImageSelect#17]
Good afternoon.

We're getting more feedback from our users. Can you please have a look at those?

1) NPE in AlbumSelectActivity, line 218

java.lang.NullPointerException
com.darsh.multipleimageselect.activities.AlbumSelectActivity$AlbumLoaderRunnable.run(AlbumSelectActivity.java:218)
java.lang.Thread.run(Thread.java:838)

2) NPE in AlbumSelectActivity, line 253

java.lang.NullPointerException
com.darsh.multipleimageselect.activities.AlbumSelectActivity$AlbumLoaderRunnable.run(AlbumSelectActivity.java:253)
java.lang.Thread.run(Thread.java:848)

3) NPE in AlbumSelectActivity, line 144

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.setLayoutParams(int)' on a null object reference
com.darsh.multipleimageselect.activities.AlbumSelectActivity.orientationBasedUI(AlbumSelectActivity.java:144)
com.darsh.multipleimageselect.activities.AlbumSelectActivity.onConfigurationChanged(AlbumSelectActivity.java:135)
android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4170)
android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:4248)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:135)
android.app.ActivityThread.main(ActivityThread.java:5422)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

**Comment by darsh2** [comment]
Looks like album loading logic needs some changes. Will update soon. Is this on specific devices only or a common occurrence?

**Comment by elenaSid** [comment]
Hi, our users have the same error:
``` 
java.lang.NullPointerException
  at com.darsh.multipleimageselect.activities.ImageSelectActivity$ImageLoaderRunnable.run(ImageSelectActivity.java:439)
       at java.lang.Thread.run(Thread.java:841) 
```
This error appears on samsung SM-G318H and SM-G313H devices

**Comment by yargray** [comment]
Hi! I got this one:
```java
java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
       at com.darsh.multipleimageselect.activities.AlbumSelectActivity$AlbumLoaderRunnable.run(AlbumSelectActivity.java:334)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by chriscborg** [comment]
Hi - I got the same error report as @yargray above. Any ideas what could be causing this cause I couldn't reproduce the issue? Apparently this is coming from a Samsung Galaxy Note 2.
