### ISSUE TITLE
Out of bound

### ISSUE THREAD

**Issue by phantuanphong** [darsh2/MultipleImageSelect#19]
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 18, size is 18
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.darsh.multipleimageselect.adapters.CustomImageSelectAdapter.getView(CustomImageSelectAdapter.java:46)
       at android.widget.AbsListView.obtainView(AbsListView.java:2467)
       at android.widget.GridView.makeAndAddView(GridView.java:1438)
       at android.widget.GridView.makeRow(GridView.java:366)
       at android.widget.GridView.fillDown(GridView.java:307)
       at android.widget.GridView.fillSpecific(GridView.java:587)
       at android.widget.GridView.layoutChildren(GridView.java:1292)
       at android.widget.AbsListView.onLayout(AbsListView.java:2230)
       at android.view.View.layout(View.java:16017)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
       at android.view.View.layout(View.java:16017)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16017)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16017)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16017)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
       at android.view.View.layout(View.java:16017)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
       at android.view.View.layout(View.java:16017)
       at android.view.ViewGroup.layout(ViewGroup.java:5181)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2483)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2180)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6598)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:572)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5631)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by darsh2** [comment]
Will look into this soon.
