### ISSUE TITLE
com.darsh.multipleimageselect.activities.ImageSelectActivity$ImageLoaderRunnable.run (ImageSelectActivity.java:439) java.lang.Thread.run (Thread.java:818)

### ISSUE THREAD

**Issue by Siddhant-Myshopup** [darsh2/MultipleImageSelect#39]
This is an error that i am getting again and again, please let me know how can i resolve it 

Exception java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
com.darsh.multipleimageselect.activities.ImageSelectActivity$ImageLoaderRunnable.run (ImageSelectActivity.java:439)
java.lang.Thread.run (Thread.java:818)

Thanks

**Comment by darsh2** [comment]
Hey, this issue is present in v0.0.4 of the library. It has been fixed [here](https://github.com/darsh2/MultipleImageSelect/commit/3474549f2c312a3e49d05a53af5f56e591e675fd). Please update your build.gradle to use the latest build of this library. You can do so by inserting the commit hash of the latest commit. 

```gradle
dependencies {
  compile 'com.github.darsh2:MultipleImageSelect:28c6d56'
}
```

**Comment by wangzhanxian** [comment]
Fatal Exception: java.lang.IllegalArgumentException: the bind value at index 1 is null
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
       at android.content.ContentResolver.query(ContentResolver.java:493)
       at android.content.ContentResolver.query(ContentResolver.java:436)
       at com.darsh.multipleimageselect.activities.ImageSelectActivity$f.run(SourceFile:16)
       at java.lang.Thread.run(Thread.java:819)

**Comment by happyer2018** [comment]
java.lang.IllegalArgumentException: the bind value at index 1 is null
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
at android.content.ContentResolver.query(ContentResolver.java:1201)
at android.content.ContentResolver.query(ContentResolver.java:1127)
at android.content.ContentResolver.query(ContentResolver.java:1083)
at com.darsh.multipleimageselect.activities.ImageSelectActivity$ImageLoaderRunnable.run(ImageSelectActivity.java:439)
at java.lang.Thread.run(Thread.java:923)
