### ISSUE TITLE
Cannot cast appbarlayout to toolbar

### ISSUE THREAD

**Issue by nicchong** [darsh2/MultipleImageSelect#40]
```
  <include
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        layout="@layout/toolbar"/>
```

id/toolbar should be used in <android.support.v7.widget.Toolbar/> instead of include tag

**Comment by darsh2** [comment]
Hey can you provide more context regarding the issue?

**Comment by nicchong** [comment]
After I include the gradle and call the AlbumSelectActivity will get the exception below

 Caused by: java.lang.ClassCastException: android.support.design.widget.AppBarLayout cannot be cast to android.support.v7.widget.Toolbar at com.darsh.multipleimageselect.activities.AlbumSelectActivity.onCreate(AlbumSelectActivity.java:69)

**Comment by kyndaqtepammy** [comment]
Mine says_`: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.support.v7.widget.Toolbar  at com.darsh.multipleimageselect.activities.AlbumSelectActivity.onCreate(AlbumSelectActivity.java:69)`_

**Comment by tahirghani9** [comment]
have you resolved this issue? i am also facing the same issue
