### ISSUE TITLE
Crashes when used with Glide version 4x

### ISSUE THREAD

**Issue by ParagKadam101** [darsh2/MultipleImageSelect#51]
I am using Glide in my project, if I use version 3x then it works fine but if I use version 4x then the app gets crashed as soon as the image selector activity is launched. 
This is the line which shows the error:-
`Glide.with(this.context).load(((Album)this.arrayList.get(position)).cover).placeholder(drawable.image_placeholder).centerCrop().into(viewHolder.imageView);`
```
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.parag.sopr-2/base.apk:classes58.dex)
                                                                          at com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:44)
                                                                          at android.widget.AbsListView.obtainView(AbsListView.java:2367)
                                                                          at android.widget.GridView.onMeasure(GridView.java:1065)
                                                                          at android.view.View.measure(View.java:19758)
                                                                          at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                          at android.view.View.measure(View.java:19758)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                          at android.view.View.measure(View.java:19758)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:19758)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:19758)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                          at android.view.View.measure(View.java:19758)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6124)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
                                                                          at android.view.View.measure(View.java:19758)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1358)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6325)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6111)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

**Comment by pingothedoer** [comment]
Did you find any solution? I am facing the same issue.

**Comment by surveshoeb** [comment]
Same issue

**Comment by surveshoeb** [comment]
Decarde your glide version in gradle to `compile 'com.github.bumptech.glide:glide:3.6.0'`

**Comment by weilong88** [comment]
Is there a way to update this library to v4 ?

**Comment by yusufcaglar-zz** [comment]
I tried exclude glide from dependency but it didn't work either. I am using surveshoeb's solution at the moment

**Comment by yusufcaglar-zz** [comment]
The only solution i found is downloading the source code and implementing it as module in android studio . Then in gradle use latest version of glide.

**Comment by surveshoeb** [comment]
Yeap you can also do that

**Comment by shreenivas-ch** [comment]
For now I had only one solution, replaced this library with other library which using latest glide version, as I need to use latest glide in my project as well as so other dependency library

**Comment by wishihab** [comment]
> For now I had only one solution, replaced this library with other library which using latest glide version, as I need to use latest glide in my project as well as so other dependency library

Any suggest of other library?

**Comment by sjd753** [comment]
forked and rescued the library. Now it's compatible with api 29 and most importantly **glide is updated to v4.12.0**
`implementation 'com.github.sjd753:MultipleImageSelect:1.0.1'`
