### ISSUE TITLE
ava.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by thezeeshan92** [darsh2/MultipleImageSelect#56]
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/xx.xxx.xx-OJFhWIjQX9_LdfytqTJqEQ==/split_lib_dependencies_apk.apk)
                      at com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:44)
                      at android.widget.AbsListView.obtainView(AbsListView.java:3189)
                      at android.widget.GridView.onMeasure(GridView.java:1102)
                      at android.view.View.measure(View.java:23296)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                      at android.view.View.measure(View.java:23296)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
                      at android.view.View.measure(View.java:23296)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at android.view.View.measure(View.java:23296)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at android.view.View.measure(View.java:23296)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                      at android.view.View.measure(View.java:23296)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                      at com.android.internal.policy.DecorView.onMeasure(DecorView.java:899)
                      at android.view.View.measure(View.java:23296)
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2886)
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1916)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2171)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7833)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                      at android.view.Choreographer.doFrame(Choreographer.java:658)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6944)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by rbsshetty** [comment]
Facing same issue on Android lollipop version 5.1. Any solution?

**Comment by pradeepMadush** [comment]
It crashes when used with Glide version 4x.. use glide:3x or use picasso instead of glide.

**Comment by sjd753** [comment]
forked and rescued the library. Now it's compatible with api 29 and most importantly **glide is updated to v4.12.0**
`implementation 'com.github.sjd753:MultipleImageSelect:1.0.1'`

**Comment by castrojr913** [comment]
I updated the library, migrating _appcompat_ libs to AndroidX and upgrading gradle files. I've set the  buildToolsVersion = 32, minSdkVersion = 23. I've also set android:exported for each Activity on AndroidManifest.xml which is required by Android 12.

`api 'com.github.castrojr913:MultipleImageSelect:1.0.1'`

**Comment by lingchenma** [comment]
> I updated the library, migrating _appcompat_ libs to AndroidX and upgrading gradle files. I've set the buildToolsVersion = 32, minSdkVersion = 23. I've also set android:exported for each Activity on AndroidManifest.xml which is required by Android 12.
> 
> `api 'com.github.castrojr913:MultipleImageSelect:1.0.1'`


Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.castrojr913:MultipleImageSelect:1.0.1.
     Searched in the following locations:
